
site_name: Sample Documentation Site
repo_url: https://github.com/squidfunk/mkdocs-material
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy
  language: en
  palette:
    - scheme: slate
      primary: black
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

# Define top-level tabs (per-language content is resolved by i18n)
nav:
  - Developer Docs:
    - Overview: developer-docs/index.md
    - TypeScript Quickstart: developer-docs/typescript.md
  - User Docs:
    - Overview: user-docs/index.md

plugins:
  - search
  - mermaid2
  - i18n:
      default_language: en
      docs_structure: folder
      reconfigure_material: true
      languages:
        - locale: en
          name: English
          default: true
          build: true
        - locale: ja
          name: 日本語
          build: true
          nav_translations:
            Developer Docs: 開発者向けドキュメント
            User Docs: ユーザー向けドキュメント
            Overview: 概要
            TypeScript Quickstart: TypeScript クイックスタート
  - git-revision-date-localized:
      type: timeago
      enable_creation_date: true
      fallback_to_build_date: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
