name: Deploy MkDocs to Pages

on:
  push:
    branches: [ "main" ]
  # Temporary: enable on PRs to test builds before merging
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0  # needed for git revision date plugin

      - name: Set up uv (Python + resolver)
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: uv sync --frozen

      - name: Build MkDocs site
        run: uv run mkdocs build --strict

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
